/**
 * Generated by einblick-sdk on 2026-06-05T13:22:21.728Z.
 * Schema source: openapi-endpoint.
 * Do not edit manually.
 */

import { createEinblickClient } from '@einblick/sdk'
import type {
  CreateEinblickClientOptions,
  EinblickAsset,
  EinblickResourceFields,
} from '@einblick/sdk'

export type EinblickSchema = {
  "site-settings": {
    name: "Site Settings"
    mode: "singleton"
    sourceType: "cms"
    fields: {
      titel?: string
      pdf?: EinblickAsset | null
    }
  }
}

export type EinblickResourceSlug = keyof EinblickSchema

export type SiteSettingsFields = EinblickResourceFields<EinblickSchema, "site-settings">

export const RESOURCE_SOURCE_TYPES = {
  "site-settings": "cms",
} as const satisfies Record<EinblickResourceSlug, "cms" | "native">

export function createGeneratedEinblickClient(
  options: Partial<CreateEinblickClientOptions> = {}
) {
  return createEinblickClient<EinblickSchema>({
    ...options,
    resourceSourceTypes: { ...RESOURCE_SOURCE_TYPES, ...options.resourceSourceTypes },
  })
}

export const createEinblick = createGeneratedEinblickClient
