/**
 * Generated by einblick-sdk on 2026-09-25T18:12:00.521Z.
 * Schema source: openapi-endpoint.
 * Do not edit manually.
 */

import { createEinblickClient } from '@einblick/sdk'
import type {
  CreateEinblickClientOptions,
  EinblickClient,
  EinblickAsset,
  EinblickResourceFields,
} from '@einblick/sdk'

export type EinblickSchema = {
  "site-settings": {
    name: "Site Settings"
    mode: "singleton"
    sourceType: "cms"
    fields: {
      titel?: string
      pdf?: EinblickAsset | null
    }
  }
}

export type EinblickResourceSlug = keyof EinblickSchema

export type SiteSettingsFields = EinblickResourceFields<EinblickSchema, "site-settings">

export type SiteSettingsWritableFields = Record<string, never>

type BaseEinblickClient = EinblickClient<EinblickSchema>

export type GeneratedEinblickResourceClients = {
  [key: string]: never
}

type GeneratedEinblickResourceClientMixin = {
  readonly resources: GeneratedEinblickResourceClients
}

export type GeneratedEinblickClient = BaseEinblickClient & GeneratedEinblickResourceClientMixin

function createGeneratedResourceClients(): GeneratedEinblickResourceClients {
  return {} as GeneratedEinblickResourceClients
}

export const RESOURCE_SOURCE_TYPES = {
  "site-settings": "cms",
} as const satisfies Record<EinblickResourceSlug, "cms" | "native">

export function createGeneratedEinblickClient(
  options: Partial<CreateEinblickClientOptions> = {}
): GeneratedEinblickClient {
  const client = createEinblickClient<EinblickSchema>({
    ...options,
    resourceSourceTypes: { ...RESOURCE_SOURCE_TYPES, ...options.resourceSourceTypes },
  })

  return Object.assign(client, {
    resources: createGeneratedResourceClients(),
  }) as GeneratedEinblickClient
}

export const createEinblick = createGeneratedEinblickClient
